version: '3'
services:

  fastapi_service:
    build: .
    env_file: "./env.env"
    command: python ./api/main.py
    ports:
      - "8080:8080"
    depends_on:
      - redis_service

  celery_service:
    build: .
    env_file: "./env.env"
    command: celery -A task_app.celery_app worker --loglevel=info
    depends_on:
      - fastapi_service
      - redis_service

#  flower_service:
#    build: .
#    env_file: "./env.env"
#    command: celery -A task_app.celery_app flower --port=5555
#    ports:
#      - "5555:5555"
#    depends_on:
#      - service_fastapi
#      - service_redis
#      - service_celery

  redis_service:
    image: redis
    container_name: container_redis
    ports:
      - "6379:6379"

  selenium_service:
    image: selenium/standalone-chrome
    container_name: container_selenium
    environment:
      VNC_NO_PASSWORD: 1
    shm_size: 2gb
    ports:
      - 4444:4444
    depends_on:
      - celery_service
